######################## default configuration ####################
baseURL = "/"
title = "Twenty Twenty Hugo for Forestry"
languageName = "En"
languageCode = "en-us"

[taxonomies]
year = "year"
month = "month"
category = "categories"

[permalinks]
post = "/posts/:year/:month/:slug/"
year = "/posts/:year/"
month = "/posts/:year/:month/"
category = "/posts/:slug/"

[params]
blog = ["posts"]